"""Issue2Patch package."""

from issue2patch.patching import (
    DEFAULT_MAX_OPERATIONS,
    DEFAULT_MAX_TOTAL_BYTES,
    FileChange,
    PatchOperation,
    PatchResult,
    apply_patch,
)
from issue2patch.orchestrator import (
    AgentAction,
    AgentConfig,
    AgentContext,
    AgentOrchestrator,
    AgentProgressEvent,
    AgentRunResult,
    FinishAction,
    InvalidModelActionError,
    ModelClient,
    ModelUsage,
    PatchAction,
    ReadFileAction,
    RunTestsAction,
    ScriptedModel,
    SearchAction,
    TerminationStatus,
    TestOutcome,
    TestRunSummary,
)
from issue2patch.models import (
    DEFAULT_DEEPSEEK_MODEL,
    DEFAULT_OPENAI_MODEL,
    DeepSeekResponsesModelClient,
    InvalidModelOutputError,
    MissingAPIKeyError,
    ModelClientError,
    ModelTransportError,
    OpenAIResponsesModelClient,
)
from issue2patch.evals import (
    DEFAULT_EVAL_RUNS,
    EvalAggregate,
    EvalReport,
    EvalRunRecord,
    EvalRunner,
    EvalTask,
    EvalTaskSummary,
    EvalValidationError,
    load_eval_suite,
    render_markdown_report,
    write_eval_reports,
)
from issue2patch.sandbox import DockerSandboxRunner, SandboxResult
from issue2patch.trace import TraceRecorder

__version__ = "0.1.0"

__all__ = [
    "FileChange",
    "PatchOperation",
    "PatchResult",
    "TraceRecorder",
    "DEFAULT_MAX_OPERATIONS",
    "DEFAULT_MAX_TOTAL_BYTES",
    "DockerSandboxRunner",
    "SandboxResult",
    "AgentAction",
    "AgentConfig",
    "AgentContext",
    "AgentOrchestrator",
    "AgentProgressEvent",
    "AgentRunResult",
    "FinishAction",
    "InvalidModelActionError",
    "ModelClient",
    "ModelUsage",
    "DEFAULT_DEEPSEEK_MODEL",
    "DEFAULT_OPENAI_MODEL",
    "DeepSeekResponsesModelClient",
    "InvalidModelOutputError",
    "MissingAPIKeyError",
    "ModelClientError",
    "ModelTransportError",
    "OpenAIResponsesModelClient",
    "DEFAULT_EVAL_RUNS",
    "EvalAggregate",
    "EvalReport",
    "EvalRunRecord",
    "EvalRunner",
    "EvalTask",
    "EvalTaskSummary",
    "EvalValidationError",
    "load_eval_suite",
    "render_markdown_report",
    "write_eval_reports",
    "PatchAction",
    "ReadFileAction",
    "RunTestsAction",
    "ScriptedModel",
    "SearchAction",
    "TerminationStatus",
    "TestOutcome",
    "TestRunSummary",
    "__version__",
    "apply_patch",
]
